//index.js
//获取应用实例
var app = getApp()
Page({
  data: {
    motto: 'Hello World',
    userInfo: {},
    show:1,
    off:0,
    mydata:{
      avatar:'/src/coveravatar.png',
      nickName:'爱是不可名zhide cuowu',
      steps:6667843,
      likes:456,
      unlikepic:'/src/unlike.png',
      likepic:'/src/liked.png',
      grade:3

    },
    mymonthdata:{
      avatar:'/src/coveravatar.png',
      nickName:'爱是不可名zhide cuowu',
      steps:66678243,
      likes:4545,
      unlikepic:'/src/unlike.png',
      likepic:'/src/liked.png',
      grade:3

    },
    friendsdata:{
        1:{
        avatar:'/src/avatar_1.png',
        nickName:'wu',
        steps:11143,
        likes:456,
        grade:3,
         },
        2:{
        avatar:'/src/avatar_2.png',
        nickName:'wudong',
        steps:843,
        likes:44,
        grade:56,
         },
         3:{
        avatar:'/src/avatar_1.png',
        nickName:'爱是不可名zhide cuowu',
        steps:666843,
        likes:456,
        grade:12,
         },
         4:{
        avatar:'/src/avatar_1.png',
        nickName:'u',
        steps:667843,
        likes:0,
        grade:309,
         },
         5:{
        avatar:'/src/avatar_2.png',
        nickName:'wu',
        steps:6667843,
        likes:456,
        grade:0,
         },
         6:{
        avatar:'/src/avatar_1.png',
        nickName:'为爱封麦',
        steps:6663,
        likes:456,
        grade:0,
         },
         7:{
        avatar:'/src/avatar_2.png',
        nickName:'为爱封麦',
        steps:6663,
        likes:456,
        grade:0,
         },
         8:{
        avatar:'/src/avatar_1.png',
        nickName:'为爱封麦',
        steps:6663,
        likes:456,
        grade:0,
         },
         9:{
        avatar:'/src/avatar_2.png',
        nickName:'为sdfg麦',
        steps:6663,
        likes:456,
        grade:0,
         },
         10:{
        avatar:'/src/avatar_1.png',
        nickName:'为爱2封麦',
        steps:6663,
        likes:456,
        grade:0,
         },
         11:{
        avatar:'/src/avatar_2.png',
        nickName:'为封麦',
        steps:6663,
        likes:456,
        grade:0,
         },
    },
     friendsmonthdata:{
        1:{
        avatar:'/src/avatar_1.png',
        nickName:'wu',
        steps:117143,
        likes:456,
        grade:3,
         },
        2:{
        avatar:'/src/avatar_2.png',
        nickName:'wudong',
        steps:843,
        likes:44,
        grade:56,
         },
         3:{
        avatar:'/src/avatar_1.png',
        nickName:'爱是不可名zhide cuowu',
        steps:66843,
        likes:456,
        grade:12,
         },
         4:{
        avatar:'/src/avatar_1.png',
        nickName:'u',
        steps:667843,
        likes:0,
        grade:309,
         },
         5:{
        avatar:'/src/avatar_2.png',
        nickName:'wu',
        steps:6667843,
        likes:6,
        grade:0,
         },
         6:{
        avatar:'/src/avatar_1.png',
        nickName:'为爱封麦',
        steps:9763,
        likes:456,
        grade:0,
         },
         7:{
        avatar:'/src/avatar_2.png',
        nickName:'为爱封麦',
        steps:8663,
        likes:456,
        grade:0,
         },
         8:{
        avatar:'/src/avatar_1.png',
        nickName:'为爱封麦',
        steps:7663,
        likes:456,
        grade:0,
         },
         9:{
        avatar:'/src/avatar_2.png',
        nickName:'为爱封麦',
        steps:6613,
        likes:456,
        grade:0,
         },
         10:{
        avatar:'/src/avatar_1.png',
        nickName:'为爱封麦',
        steps:6653,
        likes:456,
        grade:0,
         },
         11:{
        avatar:'/src/avatar_2.png',
        nickName:'为爱封麦',
        steps:6663,
        likes:456,
        grade:0,
         },
    }
  },
  //事件处理函数
  bindViewTap: function() {
    wx.navigateTo({
      url: '../logs/logs'
    })
  },
  showToday:function(){
    this.setData({
      show:1,
      off:0
    })

  },
  showMonth:function(){
    this.setData({
      show:0,
      off:1
    })
  },
  onLoad: function () {
    console.log('onLoad')
    var that = this
    //调用应用实例的方法获取全局数据
    app.getUserInfo(function(userInfo){
      //更新数据
      that.setData({
        userInfo:userInfo
      })
    })
  }
})
